CREATE TABLE `ana_review_draft` (
  `id` BIGINT NOT NULL,
  `task_id` BIGINT NOT NULL,
  `case_id` BIGINT NOT NULL,
  `doctor_user_id` BIGINT NOT NULL,
  `revised_grade` VARCHAR(16) NOT NULL,
  `revised_detections_json` JSON NULL,
  `reason_tags_json` JSON NULL,
  `note` VARCHAR(2000) NULL,
  `draft_status_code` VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  `submitted_feedback_id` BIGINT NULL,
  `version_no` INT NOT NULL DEFAULT 1,
  `org_id` BIGINT NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  `deleted_flag` BIGINT NOT NULL DEFAULT 0,
  `created_by` BIGINT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_draft_task_doctor_del` (`task_id`, `doctor_user_id`, `deleted_flag`),
  KEY `idx_review_draft_case` (`case_id`),
  KEY `idx_review_draft_org_status` (`org_id`, `draft_status_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Doctor review draft and submission state';
