CREATE TABLE `med_image_quality_check` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `image_id` BIGINT NOT NULL COMMENT '影像ID',
  `case_id` BIGINT NOT NULL COMMENT '病例ID',
  `patient_id` BIGINT NOT NULL COMMENT '患者ID',
  `check_type_code` VARCHAR(32) NOT NULL DEFAULT 'AUTO' COMMENT '质检类型(AUTO/MANUAL)',
  `check_result_code` VARCHAR(32) NOT NULL DEFAULT 'REVIEW' COMMENT '质检结果(PASS/REJECT/REVIEW)',
  `quality_score` INT NULL COMMENT '综合评分(0-100)',
  `blur_score` INT NULL COMMENT '模糊评分(0-100)',
  `exposure_score` INT NULL COMMENT '曝光评分(0-100)',
  `integrity_score` INT NULL COMMENT '完整度评分(0-100)',
  `occlusion_score` INT NULL COMMENT '遮挡评分(0-100)',
  `issue_codes_json` JSON NULL COMMENT '问题码列表',
  `suggestion_text` VARCHAR(500) NULL COMMENT '建议说明',
  `current_flag` CHAR(1) NOT NULL DEFAULT '1' COMMENT '是否当前有效记录(0/1)',
  `checked_by` BIGINT NULL COMMENT '质检人用户ID',
  `checked_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '质检时间',
  `org_id` BIGINT NOT NULL COMMENT '所属机构ID',
  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态',
  `deleted_flag` BIGINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  `remark` VARCHAR(500) NULL COMMENT '备注',
  `created_by` BIGINT NULL COMMENT '创建人',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT NULL COMMENT '更新人',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_image_checked_at` (`image_id`, `checked_at`),
  KEY `idx_case_checked_at` (`case_id`, `checked_at`),
  KEY `idx_org_result` (`org_id`, `check_result_code`),
  KEY `idx_image_current` (`image_id`, `current_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='影像质量检查表';
