package com.cariesguard.image.domain.model;

import java.time.LocalDateTime;

public record AttachmentUploadModel(
        Long attachmentId,
        String bizModuleCode,
        Long bizId,
        String fileCategoryCode,
        String assetTypeCode,
        Long sourceAttachmentId,
        String fileName,
        String originalName,
        String bucketName,
        String objectKey,
        String contentType,
        String fileExt,
        Long fileSizeBytes,
        String md5,
        String storageProviderCode,
        String visibilityCode,
        String retentionPolicyCode,
        LocalDateTime expiredAt,
        String integrityStatusCode,
        String metadataJson,
        Long uploadUserId,
        Long orgId,
        String status,
        String remark,
        Long operatorUserId) {

    public AttachmentUploadModel(Long attachmentId,
                                 String bizModuleCode,
                                 Long bizId,
                                 String fileCategoryCode,
                                 String assetTypeCode,
                                 Long sourceAttachmentId,
                                 String fileName,
                                 String originalName,
                                 String bucketName,
                                 String objectKey,
                                 String contentType,
                                 String fileExt,
                                 Long fileSizeBytes,
                                 String md5,
                                 String storageProviderCode,
                                 String visibilityCode,
                                 String retentionPolicyCode,
                                 LocalDateTime expiredAt,
                                 Long uploadUserId,
                                 Long orgId,
                                 String status,
                                 String remark,
                                 Long operatorUserId) {
        this(attachmentId, bizModuleCode, bizId, fileCategoryCode, assetTypeCode, sourceAttachmentId,
                fileName, originalName, bucketName, objectKey, contentType, fileExt, fileSizeBytes, md5,
                storageProviderCode, visibilityCode, retentionPolicyCode, expiredAt, "NORMAL", null,
                uploadUserId, orgId, status, remark, operatorUserId);
    }
}
