package com.cariesguard.image.domain.model;

import java.io.InputStream;

public record ObjectStoreCommand(
        String bucketCode,
        String objectKindCode,
        Long orgId,
        String caseNo,
        String imageTypeCode,
        Long attachmentId,
        String taskNo,
        String modelVersion,
        String assetTypeCode,
        Long relatedImageId,
        String toothCode,
        String reportTypeCode,
        Integer versionNo,
        Long operatorId,
        Long exportLogId,
        String reportNo,
        String originalFileName,
        String contentType,
        InputStream inputStream,
        long fileSizeBytes,
        String md5) {

    public static ObjectStoreCommand rawImage(String bucketCode,
                                              Long orgId,
                                              String caseNo,
                                              String imageTypeCode,
                                              Long attachmentId,
                                              String originalFileName,
                                              String contentType,
                                              InputStream inputStream,
                                              long fileSizeBytes,
                                              String md5) {
        return new ObjectStoreCommand(
                bucketCode,
                "RAW_IMAGE",
                orgId,
                caseNo,
                imageTypeCode,
                attachmentId,
                null,
                null,
                imageTypeCode,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                originalFileName,
                contentType,
                inputStream,
                fileSizeBytes,
                md5);
    }

    public static ObjectStoreCommand visualAsset(String bucketCode,
                                                 Long orgId,
                                                 String caseNo,
                                                 String taskNo,
                                                 String modelVersion,
                                                 String assetTypeCode,
                                                 Long relatedImageId,
                                                 String toothCode,
                                                 Long attachmentId,
                                                 String originalFileName,
                                                 String contentType,
                                                 InputStream inputStream,
                                                 long fileSizeBytes,
                                                 String md5) {
        return new ObjectStoreCommand(
                bucketCode,
                "VISUAL",
                orgId,
                caseNo,
                null,
                attachmentId,
                taskNo,
                modelVersion,
                assetTypeCode,
                relatedImageId,
                toothCode,
                null,
                null,
                null,
                null,
                null,
                originalFileName,
                contentType,
                inputStream,
                fileSizeBytes,
                md5);
    }

    public static ObjectStoreCommand reportPdf(String bucketCode,
                                               Long orgId,
                                               String caseNo,
                                               String reportTypeCode,
                                               Integer versionNo,
                                               String reportNo,
                                               String originalFileName,
                                               String contentType,
                                               InputStream inputStream,
                                               long fileSizeBytes,
                                               String md5) {
        return new ObjectStoreCommand(
                bucketCode,
                "REPORT",
                orgId,
                caseNo,
                null,
                null,
                null,
                null,
                reportTypeCode,
                null,
                null,
                reportTypeCode,
                versionNo,
                null,
                null,
                reportNo,
                originalFileName,
                contentType,
                inputStream,
                fileSizeBytes,
                md5);
    }

    public static ObjectStoreCommand exportFile(String bucketCode,
                                                Long orgId,
                                                Long operatorId,
                                                Long exportLogId,
                                                String reportNo,
                                                String originalFileName,
                                                String contentType,
                                                InputStream inputStream,
                                                long fileSizeBytes,
                                                String md5) {
        return new ObjectStoreCommand(
                bucketCode,
                "EXPORT",
                orgId,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                operatorId,
                exportLogId,
                reportNo,
                originalFileName,
                contentType,
                inputStream,
                fileSizeBytes,
                md5);
    }
}
