export type DiagState = 'empty' | 'scanning' | 'result'

export type RiskLevel = 'high' | 'medium' | 'low' | 'other'

export type DemoDisplayMode = 'cover' | 'contain'

export interface Annotation {
  id: number
  tooth: string
  region: string
  finding: string
  level: RiskLevel
  confidence: number
  recommendation: string
  left: number
  top: number
  width: number
  height: number
  rotate?: number
  heatLeft: number
  heatTop: number
  heatWidth: number
  heatHeight: number
  heatOpacity: number
}

export interface Diagnosis {
  level: RiskLevel
  text: string
}

export interface AnalysisResults {
  teethDetected: number
  anomalies: number
  severity: string
  confidence: number
  overallScore: number
  riskHigh: number
  riskMedium: number
  riskLow: number
  riskOther: number
  diagnoses: Diagnosis[]
}

export interface DemoCase {
  key: 'case20' | 'case10'
  fileNames: string[]
  resultImageUrl: string
  displayMode: DemoDisplayMode
  results: AnalysisResults
  annotations: Annotation[]
}

export const RISK_COLORS: Record<RiskLevel, string> = {
  high: '#ff5568',
  medium: '#ffad4d',
  low: '#35f8ff',
  other: '#a66bff',
}

export const RISK_LABELS: Record<RiskLevel, string> = {
  high: '高风险',
  medium: '中风险',
  low: '低风险',
  other: '其他异常',
}

export const MOCK_RESULTS: AnalysisResults = {
  teethDetected: 28,
  anomalies: 7,
  severity: '中高风险',
  confidence: 92.7,
  overallScore: 85,
  riskHigh: 2,
  riskMedium: 2,
  riskLow: 2,
  riskOther: 1,
  diagnoses: [
    { level: 'high', text: '右下阻生智齿与邻牙接触紧密，建议尽快结合 CBCT 进一步评估拔除时机。' },
    { level: 'high', text: '左上第二前磨牙可见深龋影，建议尽快完善去腐充填并评估髓腔受累情况。' },
    { level: 'medium', text: '右下第一磨牙牙周支持组织存在吸收征象，建议联合牙周治疗与复查。' },
    { level: 'other', text: '下前牙区可见明显牙结石沉积，建议纳入口腔卫生管理与洁治计划。' },
  ],
}

export const MOCK_ANNOTATIONS: Annotation[] = [
  {
    id: 1,
    tooth: '24',
    region: '左上第二前磨牙',
    finding: '深龋影',
    level: 'high',
    confidence: 97.2,
    recommendation: '建议尽快去腐充填，必要时评估根管治疗。',
    left: 16,
    top: 23,
    width: 12,
    height: 19,
    rotate: -9,
    heatLeft: 12,
    heatTop: 18,
    heatWidth: 22,
    heatHeight: 26,
    heatOpacity: 0.78,
  },
  {
    id: 2,
    tooth: '48',
    region: '右下阻生智齿区',
    finding: '阻生智齿压迫',
    level: 'high',
    confidence: 95.8,
    recommendation: '建议口腔外科会诊，评估拔除路径及邻牙保护方案。',
    left: 78,
    top: 50,
    width: 14,
    height: 20,
    rotate: 8,
    heatLeft: 73,
    heatTop: 45,
    heatWidth: 22,
    heatHeight: 28,
    heatOpacity: 0.82,
  },
  {
    id: 3,
    tooth: '46',
    region: '右下第一磨牙',
    finding: '牙周骨吸收',
    level: 'medium',
    confidence: 91.4,
    recommendation: '建议完善牙周检查，进行龈下洁治并观察骨改建情况。',
    left: 63,
    top: 46,
    width: 13,
    height: 19,
    rotate: 4,
    heatLeft: 58,
    heatTop: 41,
    heatWidth: 22,
    heatHeight: 27,
    heatOpacity: 0.7,
  },
  {
    id: 4,
    tooth: '11-21',
    region: '上前牙区',
    finding: '釉质脱矿',
    level: 'low',
    confidence: 88.6,
    recommendation: '建议强化氟化和日常口腔清洁，三个月后复查矿化状态。',
    left: 43,
    top: 16,
    width: 14,
    height: 18,
    rotate: 0,
    heatLeft: 39,
    heatTop: 12,
    heatWidth: 22,
    heatHeight: 23,
    heatOpacity: 0.56,
  },
  {
    id: 5,
    tooth: '36',
    region: '左下第一磨牙',
    finding: '充填体边缘继发龋',
    level: 'medium',
    confidence: 89.7,
    recommendation: '建议拆除旧修复体后重新评估龋坏范围并制定修复方案。',
    left: 26,
    top: 50,
    width: 14,
    height: 21,
    rotate: -4,
    heatLeft: 21,
    heatTop: 45,
    heatWidth: 23,
    heatHeight: 28,
    heatOpacity: 0.68,
  },
  {
    id: 6,
    tooth: '17',
    region: '右上第二磨牙',
    finding: '咬合面裂隙敏感',
    level: 'low',
    confidence: 86.9,
    recommendation: '建议结合临床探诊，必要时进行窝沟封闭或早期干预。',
    left: 70,
    top: 23,
    width: 11,
    height: 17,
    rotate: 6,
    heatLeft: 66,
    heatTop: 18,
    heatWidth: 18,
    heatHeight: 22,
    heatOpacity: 0.52,
  },
  {
    id: 7,
    tooth: '33-43',
    region: '下前牙区',
    finding: '牙结石沉积',
    level: 'other',
    confidence: 84.1,
    recommendation: '建议安排洁治并配合个性化刷牙及牙线使用指导。',
    left: 42,
    top: 60,
    width: 18,
    height: 14,
    rotate: 0,
    heatLeft: 36,
    heatTop: 56,
    heatWidth: 28,
    heatHeight: 18,
    heatOpacity: 0.58,
  },
]

const CASE_20_RESULTS: AnalysisResults = {
  teethDetected: 26,
  anomalies: 6,
  severity: '高风险',
  confidence: 93.1,
  overallScore: 85,
  riskHigh: 2,
  riskMedium: 1,
  riskLow: 2,
  riskOther: 1,
  diagnoses: [
    { level: 'high', text: '左下阻生智齿区及右上磨牙区存在明确高风险病灶，建议优先安排临床复核。' },
    { level: 'medium', text: '左下第一磨牙邻面可见中度吸收样改变，建议完善邻接面检查与牙周评估。' },
    { level: 'low', text: '右上后牙裂隙区与前磨牙区见轻度异常信号，建议纳入随访与防龋管理。' },
    { level: 'other', text: '右下后牙区存在沉积类影像特征，建议同步进行口腔卫生与洁治评估。' },
  ],
}

const CASE_20_ANNOTATIONS: Annotation[] = [
  {
    id: 1,
    tooth: '27',
    region: '左上第二磨牙',
    finding: '深龋影',
    level: 'high',
    confidence: 96.4,
    recommendation: '建议尽快完善去腐充填，并评估是否累及髓角。',
    left: 66.4,
    top: 41.5,
    width: 5.2,
    height: 14.9,
    rotate: 2,
    heatLeft: 65.7,
    heatTop: 39.7,
    heatWidth: 8,
    heatHeight: 18.8,
    heatOpacity: 0.76,
  },
  {
    id: 2,
    tooth: '16',
    region: '右上第一磨牙',
    finding: '釉质脱矿',
    level: 'low',
    confidence: 87.3,
    recommendation: '建议加强氟化和咬合面封闭，纳入定期复查。',
    left: 25.6,
    top: 41.2,
    width: 3.5,
    height: 15.4,
    rotate: -4,
    heatLeft: 24.8,
    heatTop: 39.7,
    heatWidth: 6,
    heatHeight: 18.4,
    heatOpacity: 0.58,
  },
  {
    id: 3,
    tooth: '15',
    region: '右上第二前磨牙',
    finding: '裂隙敏感区',
    level: 'low',
    confidence: 85.6,
    recommendation: '建议结合临床探诊，必要时进行窝沟封闭处理。',
    left: 29.6,
    top: 44.1,
    width: 3.3,
    height: 12.6,
    rotate: -3,
    heatLeft: 28.7,
    heatTop: 42.2,
    heatWidth: 5.5,
    heatHeight: 15.5,
    heatOpacity: 0.6,
  },
  {
    id: 4,
    tooth: '36',
    region: '左下第一磨牙邻面',
    finding: '牙周骨吸收',
    level: 'medium',
    confidence: 91.7,
    recommendation: '建议完善牙周测诊并结合片上骨改建情况制定治疗方案。',
    left: 60.2,
    top: 63,
    width: 5.4,
    height: 4.8,
    rotate: 0,
    heatLeft: 59.2,
    heatTop: 61.8,
    heatWidth: 7,
    heatHeight: 7.2,
    heatOpacity: 0.7,
  },
  {
    id: 5,
    tooth: '38区',
    region: '左下阻生智齿区',
    finding: '阻生智齿压迫',
    level: 'high',
    confidence: 95.1,
    recommendation: '建议口腔外科评估拔除路径，并关注邻牙远中骨质状态。',
    left: 66.1,
    top: 61,
    width: 6,
    height: 16.6,
    rotate: 1,
    heatLeft: 64.6,
    heatTop: 59,
    heatWidth: 7.8,
    heatHeight: 19.5,
    heatOpacity: 0.82,
  },
  {
    id: 6,
    tooth: '46-47',
    region: '右下后牙咬合面',
    finding: '牙结石沉积',
    level: 'other',
    confidence: 84.8,
    recommendation: '建议安排洁治，并结合口腔卫生习惯进行个体化宣教。',
    left: 25.6,
    top: 61.5,
    width: 4.9,
    height: 6.3,
    rotate: 0,
    heatLeft: 24.8,
    heatTop: 60.6,
    heatWidth: 6.4,
    heatHeight: 8,
    heatOpacity: 0.56,
  },
]

const CASE_10_RESULTS: AnalysisResults = {
  teethDetected: 28,
  anomalies: 10,
  severity: '高风险',
  confidence: 94.3,
  overallScore: 88,
  riskHigh: 4,
  riskMedium: 1,
  riskLow: 3,
  riskOther: 2,
  diagnoses: [
    { level: 'high', text: '右侧后牙区可见多处明显龋坏与邻面透亮影，建议优先安排修复前评估。' },
    { level: 'high', text: '下颌后牙远中及邻面存在连续高风险病灶，建议结合临床探诊尽快干预。' },
    { level: 'medium', text: '充填体边缘区域见继发龋可疑信号，建议拆旧修复体后复核龋坏范围。' },
    { level: 'other', text: '下颌前磨牙邻根区存在异常透亮影，建议结合牙髓活力与根尖片进一步鉴别。' },
  ],
}

const CASE_10_ANNOTATIONS: Annotation[] = [
  {
    id: 1,
    tooth: '14',
    region: '上颌第一前磨牙邻面',
    finding: '邻面脱矿',
    level: 'low',
    confidence: 86.8,
    recommendation: '建议加强氟化和邻面清洁，三个月后复查。',
    left: 22.5,
    top: 30.2,
    width: 3.8,
    height: 8.8,
    rotate: -8,
    heatLeft: 21.3,
    heatTop: 29,
    heatWidth: 6.2,
    heatHeight: 11.6,
    heatOpacity: 0.58,
  },
  {
    id: 2,
    tooth: '15',
    region: '上颌第二前磨牙邻面',
    finding: '透亮影增高',
    level: 'low',
    confidence: 88.9,
    recommendation: '建议结合探诊与冷测，评估是否需要早期充填。',
    left: 32.4,
    top: 31.7,
    width: 4.2,
    height: 11.5,
    rotate: -4,
    heatLeft: 31.1,
    heatTop: 30.2,
    heatWidth: 6.5,
    heatHeight: 14.8,
    heatOpacity: 0.62,
  },
  {
    id: 3,
    tooth: '16',
    region: '上颌第一磨牙近中',
    finding: '浅表脱矿',
    level: 'low',
    confidence: 84.7,
    recommendation: '建议纳入随访，结合局部防龋处理。',
    left: 41,
    top: 33,
    width: 2.7,
    height: 7.6,
    rotate: -3,
    heatLeft: 40,
    heatTop: 31.7,
    heatWidth: 4.8,
    heatHeight: 10.5,
    heatOpacity: 0.54,
  },
  {
    id: 4,
    tooth: '25',
    region: '上颌第二前磨牙远中',
    finding: '邻面龋损',
    level: 'high',
    confidence: 95.8,
    recommendation: '建议尽快去腐充填，并评估龋坏向髓腔发展的深度。',
    left: 63.6,
    top: 34,
    width: 3.3,
    height: 7.2,
    rotate: -6,
    heatLeft: 62.5,
    heatTop: 32.4,
    heatWidth: 5.8,
    heatHeight: 10.2,
    heatOpacity: 0.78,
  },
  {
    id: 5,
    tooth: '26',
    region: '上颌第一磨牙邻面',
    finding: '深龋影',
    level: 'high',
    confidence: 96.9,
    recommendation: '建议优先处理龋坏区域，必要时联合牙髓诊断。',
    left: 76.4,
    top: 33,
    width: 3.3,
    height: 10,
    rotate: -4,
    heatLeft: 75,
    heatTop: 31.4,
    heatWidth: 6,
    heatHeight: 13.2,
    heatOpacity: 0.82,
  },
  {
    id: 6,
    tooth: '44',
    region: '下颌第一前磨牙根旁',
    finding: '根旁异常透亮影',
    level: 'other',
    confidence: 83.5,
    recommendation: '建议结合根尖片与牙髓活力测试进一步鉴别。',
    left: 26.1,
    top: 56,
    width: 3.4,
    height: 7.8,
    rotate: -5,
    heatLeft: 24.7,
    heatTop: 54.6,
    heatWidth: 5.8,
    heatHeight: 10.8,
    heatOpacity: 0.6,
  },
  {
    id: 7,
    tooth: '45',
    region: '下颌第二前磨牙根旁',
    finding: '根面异常影',
    level: 'other',
    confidence: 82.4,
    recommendation: '建议结合临床症状和根尖片复核根旁骨质状态。',
    left: 35.7,
    top: 57,
    width: 2.7,
    height: 8.2,
    rotate: -7,
    heatLeft: 34.6,
    heatTop: 55.3,
    heatWidth: 4.8,
    heatHeight: 10.9,
    heatOpacity: 0.56,
  },
  {
    id: 8,
    tooth: '36',
    region: '下颌第一磨牙充填体边缘',
    finding: '继发龋可疑',
    level: 'medium',
    confidence: 90.8,
    recommendation: '建议拆除旧修复体后重新评估龋坏范围并制定修复方案。',
    left: 61,
    top: 53.5,
    width: 7.4,
    height: 4.6,
    rotate: 0,
    heatLeft: 59.2,
    heatTop: 51.8,
    heatWidth: 10.5,
    heatHeight: 7.6,
    heatOpacity: 0.72,
  },
  {
    id: 9,
    tooth: '36',
    region: '下颌第一磨牙远中',
    finding: '邻面龋损',
    level: 'high',
    confidence: 94.7,
    recommendation: '建议尽快处理远中龋坏，并评估牙体保存条件。',
    left: 67.3,
    top: 61.1,
    width: 3.5,
    height: 6.1,
    rotate: -3,
    heatLeft: 66.2,
    heatTop: 59.2,
    heatWidth: 5.8,
    heatHeight: 8.8,
    heatOpacity: 0.8,
  },
  {
    id: 10,
    tooth: '37',
    region: '下颌第二磨牙咬合面',
    finding: '咬合面龋坏',
    level: 'high',
    confidence: 93.9,
    recommendation: '建议尽快完善修复处理，并检查邻牙接触点与咬合关系。',
    left: 76.5,
    top: 52,
    width: 6,
    height: 4.6,
    rotate: 0,
    heatLeft: 74.8,
    heatTop: 50.6,
    heatWidth: 9,
    heatHeight: 7.2,
    heatOpacity: 0.78,
  },
]

export const DEMO_CASES: DemoCase[] = [
  {
    key: 'case20',
    fileNames: ['7_c1.jpg', '7_c1.jpeg', '7_c1.png', '20show.png'],
    resultImageUrl: '/20show.png',
    displayMode: 'cover',
    results: CASE_20_RESULTS,
    annotations: CASE_20_ANNOTATIONS,
  },
  {
    key: 'case10',
    fileNames: ['3_c1.jpg', '3_c1.jpeg', 'show10.png'],
    resultImageUrl: '/show10.png',
    displayMode: 'contain',
    results: CASE_10_RESULTS,
    annotations: CASE_10_ANNOTATIONS,
  },
]
